config/routes.rb
Ezbk::Application.routes.draw do
  root :to => 'accounts#index'
  get 'accounts/autocomplete_account_name'
  get 'transaction_entries/autocomplete_account_name' => 'accounts#autocomplete_account_name'
  get 'tranxactions/autocomplete_transaction_tostring'
  post 'tranxactions/quick_create'
  post 'tranxactions/preview_fare_bus'
  post 'tranxactions/preview_fare_mtr'

  resource :user_session
  match 'login' => "user_sessions#new", :as => 'login', via: [:get, :post]
  match 'logout' => "user_sessions#destroy", :as => 'logout', via: [:get, :post, :delete]
  resources :users

  get 'accounts/expense_report' => 'accounts#report'
  resources :accounts
  resources :transaction_entries
  resources :tranxactions do
    resources :transaction_entries
  end

end

app/controllers/tranxactions_controller.rb
require 'net/http'
require 'nokogiri'
require 'open-uri'
require 'iconv'

class TranxactionsController < ApplicationController
  before_action :require_user
  before_action :set_page_name

  def set_page_name
    @page_name = "transactions"
  end

  def remove_width_styles(html)
    tmp = html.gsub(/style="(.*?)"/, "")
    return tmp.gsub(/width="(.*?)"/, "")
  end

  def preview_fare_bus
    type = params[:type]
    route_no = params[:route_no]
    case type
    when "KMB"
      url = "http://www.i-busnet.com/busroute/kmb/kmbr#{route_no.downcase}.php"
    when "LWB"
      url = "http://www.i-busnet.com/busroute/lwb/lwbr#{route_no.downcase}.php"
    when "CTB"
      url = "http://www.i-busnet.com/busroute/ctb/ctbr#{route_no.downcase}.php"
    when "NWFB"
      url = "http://www.i-busnet.com/busroute/nwfb/nwfbr#{route_no.downcase}.php"
    when "HBB"
      url = "http://www.i-busnet.com/busroute/harbour/harbourr#{route_no.downcase}.php"
    else
      render html: "Invalid bus type!"
    end
    ret = '<p><a target="_blank" href="' + url + '">' + url + '</a></p>'

    ic = Iconv.new('utf-8', 'big5')
    begin
      doc = Nokogiri::HTML(open(url), nil, 'big5')
      doc.xpath('//@src').remove  # remove dead img src
      unwanted_nodes = [
        'script',
        'img'
      ]
      doc.search(unwanted_nodes.join(", ")).each do |src|
        src.remove
      end

      # for normal routes, there are 5 <tr> nodes, 3rd and 4th are the two directions
      # for circular routes, there are 4 <tr> nodes, the 3rd is the one we need
      selectors = [
        'div#ypaAdWrapper-List4 ~ table > tr > td > table > tr:nth-child(3) > td:first-child',
        'div#ypaAdWrapper-List4 ~ table > tr > td > table > tr:nth-child(4) > td:first-child:not(:last-child)',
      ]
      doc.css(selectors.join(", ")).each do |el|
        ret = ret + '<table class="detailTable"><tr>' + ic.iconv(remove_width_styles(el.to_s)) + '</tr></table>'
      end
    rescue => e
      ret = ret + e.message
    end
    render html: ret.html_safe
  end

  def preview_fare_mtr
    from = params[:from]
    to = params[:to]
    from_id = get_mtr_station_id(from)
    to_id = get_mtr_station_id(to)
    if from_id == -1 or to_id == -1
      render html: ''
      return
    end
    url = "https://checkfare.swiftzer.net/checkfare14.php/zh/#{from_id},#{to_id}/0/0/x/0"
    mtr_doc = Nokogiri::HTML(open(url))

    ret = '<p><a target="_blank" href="' + url + '">' + url + '</a></p>'
    ret = ret + '<h3>' + from.strip + ' - ' + to.strip + '</h3>'
    mtr_doc.css('main div.rge_table table').each do |el|
      ret = ret + el.to_s
    end
    render html: ret.html_safe
  end

  def autocomplete_transaction_tostring
    where_sql = params[:term].split.map do |term|
                  "(tranxactions.description ilike '%#{term}%' or
                    accounts.name ilike '%#{term}%' or
                    cast(transaction_entries.debit_amount as CHAR(11)) like '%#{term}%')"
                end.join(" AND ")
    transactions = current_user_transactions.joins(:transaction_entries => :account).where(where_sql).limit(100).reduce(Hash.new) do |list, t|
      list[t.id] = t.tostring if !list.has_value?(t.tostring)
      list
    end
    @return_list = []
    transactions.each {|id,value| @return_list.push({:id => id, :value => value})}
    render :json => @return_list
  end


  # GET /tranxactions
  # GET /tranxactions.json
  def index
    start_date = params[:start_date].nil? ? "1970-01-01 00:00:00" : params[:start_date]
    end_date = params[:end_date].nil? ? "2100-01-01 00:00:00" : params[:end_date]
    @transactions = Tranxaction.of_user(current_user).
                    where("transaction_date" => (start_date)..(end_date)).
                    paginate(:page => params[:page]).
                    order("transaction_date DESC, id DESC").distinct

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @transactions }
    end
  end

  # GET /tranxactions/1
  # GET /tranxactions/1.json
  def show
    @transaction = Tranxaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @transaction }
    end
  end

  # GET /tranxactions/new
  # GET /tranxactions/new.json
  def new
    @transaction = Tranxaction.new

    2.times do
      transaction_entry = @transaction.transaction_entries.build
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @transaction }
    end
  end

  # GET /tranxactions/1/edit
  def edit
    @transaction = Tranxaction.find(params[:id])
  end

  # POST /tranxactions/quick_create
  def quick_create
    if params[:tranxaction_id].blank?
      redirect_to tranxactions_path, :alert => 'No existing transaction selected for quick create'
      return
    end
    existing = Tranxaction.find(params[:tranxaction_id])
    @transaction = existing.dup
    @transaction.transaction_entries << existing.transaction_entries.collect { |t| t.dup }
    @transaction.transaction_date = params[:transaction_date]
    respond_to do |format|
      if @transaction.save
        if params[:edit]
          format.html { redirect_to "/tranxactions/#{@transaction.id}/edit", :notice => 'Transaction was successfully created.' }
        else
          format.html { redirect_to tranxactions_path, :notice => 'Transaction was successfully created.' }
        end
        format.json { render :json => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :action => "new" }
        format.json { render :json => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # POST /tranxactions
  # POST /tranxactions.json
  def create
    #@transaction = Tranxaction.new(params[:tranxaction])
    @transaction = Tranxaction.new(params.require(:tranxaction).permit(:transaction_date, :description, { transaction_entries_attributes: [:debit_amount, :tranxaction_id, :account_id]}))

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, :notice => 'Transaction was successfully created.' }
        format.json { render :json => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :action => "new" }
        format.json { render :json => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tranxactions/1
  # PUT /tranxactions/1.json
  def update
    @transaction = Tranxaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params.require(:tranxaction).permit(:transaction_date, :description, { transaction_entries_attributes: [:debit_amount, :tranxaction_id, :account_id, :id, :_destroy]}))
        format.html { redirect_to @transaction, :notice => 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tranxactions/1
  # DELETE /tranxactions/1.json
  def destroy
    @transaction = Tranxaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to tranxactions_url }
      format.json { head :no_content }
    end
  end

  private

  def current_user_transactions
    Tranxaction.of_user(current_user)
  end

  def get_mtr_station_id(station_name)
    mtr_codes = {
      "Admiralty" => 2,
      "Airport" => 47,
      "AsiaWorld-Expo" => 56,
      "Austin" => 111,
      "Causeway Bay" => 28,
      "Central" => 1,
      "Chai Wan" => 37,
      "Che Kung Temple" => 96,
      "Cheung Sha Wan" => 18,
      "Choi Hung" => 12,
      "City One" => 98,
      "Diamond Hill" => 11,
      "Disneyland Resort" => 55,
      "East Tsim Sha Tsui" => 80,
      "Fanling" => 74,
      "Fo Tan" => 69,
      "Fortress Hill" => 30,
      "Hang Hau" => 51,
      "Heng Fa Chuen" => 36,
      "Heng On" => 101,
      "HKU" => 82,
      "Ho Man Tin" => 84,
      "Hong Kong" => 39, # or 44
      "Hung Hom" => 64,
      "Jordan" => 4,
      "Kam Sheung Road" => 115,
      "Kennedy Town" => 83,
      "Kowloon Bay" => 13,
      "Kowloon Tong" => 8,
      "Kowloon" => 40, # or 45
      "Kwai Fong" => 22,
      "Kwai Hing" => 23,
      "Kwun Tong" => 15,
      "Lai Chi Kok" => 19,
      "Lai King" => 21,
      "Lam Tin" => 38,
      "Lei Tung" => 88,
      "Lo Wu" => 76,
      "LOHAS Park" => 57,
      "Lok Fu" => 9,
      "Lok Ma Chau" => 78,
      "Long Ping" => 117,
      "Ma On Shan" => 102,
      "Mei Foo" => 20,
      "Mong Kok East" => 65,
      "Mong Kok" => 6,
      "Nam Cheong" => 53,
      "Ngau Tau Kok" => 14,
      "North Point" => 31,
      "Ocean Park" => 86,
      "Olympic" => 41,
      "Po Lam" => 52,
      "Prince Edward" => 16,
      "Quarry Bay" => 32,
      "Racecourse" => 70,
      "Sai Wan Ho" => 34,
      "Sai Ying Pun" => 81,
      "Sha Tin Wai" => 97,
      "Sha Tin" => 68,
      "Sham Shui Po" => 17,
      "Shau Kei Wan" => 35,
      "Shek Kip Mei" => 7,
      "Shek Mun" => 99,
      "Sheung Shui" => 75,
      "Sheung Wan" => 26,
      "Siu Hong" => 119,
      "South Horizons" => 89,
      "Sunny Bay" => 54,
      "Tai Koo" => 33,
      "Tai Po Market" => 72,
      "Tai Shui Hang" => 100,
      "Tai Wai" => 67,
      "Tai Wo Hau" => 24,
      "Tai Wo" => 73,
      "Tin Hau" => 29,
      "Tin Shui Wai" => 118,
      "Tiu Keng Leng" => 49,
      "Tseung Kwan O" => 50,
      "Tsim Sha Tsui" => 3,
      "Tsing Yi" => 42, # or 46
      "Tsuen Wan West" => 114,
      "Tsuen Wan" => 25,
      "Tuen Mun" => 120,
      "Tung Chung" => 43,
      "University" => 71,
      "Wan Chai" => 27,
      "Whampoa" => 85,
      "Wong Chuk Hang" => 87,
      "Wong Tai Sin" => 10,
      "Wu Kai Sha" => 103,
      "Yau Ma Tei" => 5,
      "Yau Tong" => 48,
      "Yuen Long" => 116
    }

app/views/tranxactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div id='transaction-meta-data'>
    <div class="field">
      <%= f.label :transaction_date %><br />
      <%= f.text_field :transaction_date, :tabindex => autotab, :class => 'date' %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description, :tabindex => autotab %>
    </div>
  </div>
  <table id='hint-container' style='display: none;'>
    <tr><td>Fare:</td><td id="hint-details-fare">N/A</td></tr>
    <tr><td>From:</td><td id="hint-details-from">N/A</td></tr>
    <tr><td>To:</td><td id="hint-details-to">N/A</td></tr>
  </table>

  <div class="field clear">
    <table class="center">
      <thead>
      <tr>
          <th>Account</th>
          <th>Debit Amount</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="transaction-entries-input">
        <%= f.fields_for :transaction_entries do |transaction_entry| %>
          <%= render "transaction_entry_fields", :f => transaction_entry %>
        <% end %>
        <tr>
          <td>
            <%= link_to_add_fields "Add Entry", f, :transaction_entries, {:tabindex => 9999, :id => "add-transaction-entry", :"container-tag" => "tr" } %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="actions">
    <%= f.submit ( f.object.new_record? ? "Create" : "Update"), :tabindex => autotab %>
  </div>
<% end %>
<div id="hint-details-panel" style="display: none;">
  <p style="display: none;">Route: <span id="loading-route">N/A</span></p>
  <div id="hint-details"></div>
</div>

<% content_for :javascripts do %>
<script type="text/javascript">

$(document).on('change', '.input-debit-amount', function(event){
  if($(this).val() != "") $(this).addClass("manual-input");
  else $(this).removeClass("manual-input");
  setRemainingAmount();
});
$(document).on('click', '.remove-transaction-entry', function(event){
  setRemainingAmount();
});
function setRemainingAmount(){
  $(".input-debit-amount:not(.manual-input)").each(function(index, e){
    $(e).val("");
  });

  var total = 0.0;
  $(".input-debit-amount.manual-input").filter(":visible").each(function(i,e){ total+=parseFloat($(e).val()); });
  if(total.toFixed(2) == "0.00") return ;
  if($(".input-debit-amount:not(.manual-input)").filter(":visible").length == 0){
    var add_transaction_entry_element = $('#add-transaction-entry');
    var scripts = add_transaction_entry_element.attr('onclick');
    scripts = scripts.replace(/add_fields\(this/, "add_fields($('#add-transaction-entry')");
    eval(scripts);
  }
  $(".input-debit-amount:not(.manual-input):visible:first").val(-total.toFixed(2));
}

  $('#new_transaction').validate({
    ignore: [],
    errorLabelContainer: "#form-validation-messages",
    wrapper: 'li',
    rules: {
      tranxaction_id: {
        required: true,
        minlength: 1
      },
      transaction_date: {
        required: true,
        dateISO: true,
        rangelength: [10,10]
      }
    },
    messages: {
      transaction_date: "Please enter a valid transaction date (YYYY-MM-DD)",
      tranxaction_id:   "Please select an existing transaction"
    }
  });

var autoCompleteTypes = ['KMB', 'LWB', 'CTB', 'NWFB', 'HBB', 'MTR'];
function parseBusDescription(text) {
  var result = {
    'type': null,
    'routeNo': null,
    'from': null,
    'to': null,
  };
  var busTypes = ['KMB', 'LWB', 'CTB', 'NWFB', 'HBB'];
  var spacePos = text.indexOf(' ');
  if (spacePos === -1) {
    return result;
  }
  var type = text.substr(0, spacePos);
  if (busTypes.indexOf(type) === -1) {
    return result;
  }
  result.type = type;

  var next_space_pos = text.indexOf(' ', spacePos + 1);
  if (next_space_pos === -1) {
    return result;
  }
  result.routeNo = text.substr(spacePos + 1, next_space_pos - spacePos - 1);

  var next_hyphen_pos = text.indexOf('-', next_space_pos);
  if (next_hyphen_pos !== -1) {
    result.from = text.substr(next_space_pos + 1, next_hyphen_pos - next_space_pos - 1).trim();
    result.to = text.substr(next_hyphen_pos + 1).trim();
  } else {
    result.from = text.substr(next_space_pos + 1).trim();
  }

  return result;
}

$(document).on('keyup', '#tranxaction_description', function bus(event) {
  var result = parseBusDescription($(this).val());
  if (!result.type || !result.routeNo) {
    return;
  }
  loading_route = $('#loading-route').text();
  if (result.routeNo != loading_route) {
    loadBusRouteDetails(result.type, result.routeNo);
  }
  previewFareBus($(this).val());
  if (autoCompleteTypes.indexOf(result.type) === -1) {
    hideHintPanel();
    hideHintDetailsPanel();
  }
});
$(document).on('change', '#tranxaction_description', function mtr(event) {
  var text = $(this).val();
  if (text.substr(0, 4) !== "MTR ") return;
  var next_hyphen_pos = text.indexOf("-");
  if (next_hyphen_pos === -1) return;
  var from = text.substr(4, next_hyphen_pos-4).trim();
  next_bracket_pos = text.indexOf("(");
  var to = text.substr(
    next_hyphen_pos+1,
    next_bracket_pos === -1 ? text.length - next_hyphen_pos - 1 : next_bracket_pos - next_hyphen_pos - 1
  ).trim();
  if (!from || !to) return;
  previewFareMtr(from, to);
});

function showHintDetailsPanel() {
  $('#hint-details-panel').show();
}
function hideHintDetailsPanel() {
  $('#hint-details-panel').hide();
}
function showHintPanel(hint) {
  $('#hint-container').show();
}
function hideHintPanel() {
  $('#hint-container').hide();
}

function previewFareMtr(from, to) {
  showHintPanel();
  setFrom(from);
  setTo(to);
  setFare("loading...");

  $('#hint-details').load('/tranxactions/preview_fare_mtr', {
    'from': from,
    'to': to
  }, function(responseText) {
    if (responseText.trim() == '') {
      setFare('Error');
      setFrom(from);
      setTo(to);
      hideHintDetailsPanel();
      return;
    }
    var octopusFare = $('#hint-details tr:last-child td:last-child').text();
    setFare(octopusFare);
    setFrom(from);
    setTo(to);
    showHintDetailsPanel();
  });
}

function loadBusRouteDetails(type, route_no) {
  $('#loading-route').text(route_no);
  $('#hint-details').text('');
  $('#hint-details').load('/tranxactions/preview_fare_bus', {
    'type': type,
    'route_no': route_no
  }, function(responseText) {
    if (responseText.trim() == '') {
      hideHintPanel();
      hideHintDetailsPanel();
      return;
    }
    showHintDetailsPanel();
    previewFareBus($('#tranxaction_description').val());
  });
}

function setFare(fare) {
  $('#hint-details-fare').text(fare);
}
function setFrom(from) {
  $('#hint-details-from').text(from);
}
function setTo(to) {
  $('#hint-details-to').text(to);
}

function showEmptyHint() {
  setFare('N/A');
  setFrom('N/A');
  setTo('N/A');
}

function previewFareBus(text) {
  showHintPanel();
  showEmptyHint();
  var result = parseBusDescription(text);
  if (!result.from && !result.to) {
    return;
  }

  $('.detailTable').find('td').css('background-color', 'transparent');

  $('.detailTable').each(function(index) {
    var fromResult = [];
    if (result.from) {
      fromResult = $(this).find('td:nth-child(3):contains("' + result.from + '")');
    }
    var toResult = [];
    if (result.to) {
      toResult = $(this).find('td:nth-child(3):contains("' + result.to + '")');
    }

    if (fromResult.length > 0) {
      setFrom($(fromResult[0]).text());
      fromResult.css('background-color', 'yellow');
    }
    if (toResult.length > 0) {
      setTo($(toResult[toResult.length - 1]).text());
      toResult.css('background-color', 'cyan');
    }

    if (fromResult.length > 0 && toResult.length > 0) {
      fromResult.filter(toResult).css('background-color', 'lime');
      var fromNode = $(fromResult[0]).closest('tr');
      var toNode = $(toResult[toResult.length-1]).closest('tr');
      if (fromNode.nextAll().filter(toNode).length !== 0) {
        var fare = fromNode.find('td:nth-child(4)').text();
        setFare(fare);
        setFrom($(fromResult[0]).text());
        setTo($(toResult[toResult.length - 1]).text());
        return false;
      }
    }
  })
}
</script>
<% end %>

app/views/tranxactions/_quick_create.html.erb
<div id="transaction-quick-create">
<h3>Instant Create</h3>
  <ul id="form-validation-messages" style="display: none;"></ul>
  <%= form_tag tranxactions_quick_create_path, :id => 'quick-create-form' do %>
    <span class="field">
      <%= label_tag 'transaction_date', 'Date:' %>
      <%= text_field_tag 'transaction_date', (DateTime.now - 7.hours).in_time_zone.to_date.to_s, :tabindex => autotab, :class => 'date required' %>
    </span>
    <span class="field">
      <%= label_tag 'tranxaction_id', 'Transaction:' %>
      <%= hidden_field_tag 'tranxaction_id', '', :class => 'required' %>
      <%= autocomplete_field_tag 'keyword', '', tranxactions_autocomplete_transaction_tostring_path, :tabindex => autotab, :"data-id-element" => '#tranxaction_id', :class => 'transaction-tostring', :delay => 500 %>
    </span>
    <span class="field">
      <%= check_box_tag 'edit', 'edit', false, :tabindex => autotab %>
      <%= label_tag 'edit', 'Edit after Create' %>
    </span>
    <span class="actions">
      <%= submit_tag "Create", :tabindex => autotab %>
    </span>
  <% end %>
</div>

<% content_for :javascripts do %>
<script type="text/javascript">
  $('#quick-create-form').validate({
/*    debug: true,*/
    ignore: [],
    errorLabelContainer: "#form-validation-messages",
    wrapper: 'li',
    rules: {
      tranxaction_id: {
        required: true,
        minlength: 1
      },
      transaction_date: {
        required: true,
        dateISO: true,
        rangelength: [10,10]
      }
    },
    messages: {
      transaction_date: "Please enter a valid transaction date (YYYY-MM-DD)",
      tranxaction_id:   "Please select an existing transaction"
    }
  });
</script>
<% end %>

app/views/tranxactions/_transaction_entries.html.erb
<table class="transaction-list">
  <tr>
    <th></th>
    <th></th>
    <th>Date</th>
    <th>Transaction Description</th>
    <th>Account</th>
    <th>Debit Amount</th>
  </tr>
<% if tranxactions.each do |transaction| %>
  <tr class="transaction-info">
    <td class="top"><div class="button"><%= link_to edit_icon, edit_tranxaction_path(transaction) %></div></td>
    <td class="top"><div class="button"><%= link_to destroy_icon, transaction, :confirm => 'Are you sure?', :method => :delete %></div></td>
    <td class="top date"><%= transaction.transaction_date %></td>
    <td class="top description" colspan="3"><%= transaction.description %></td>
    <td></td>
    <td></td>
  </tr>
  <% transaction.transaction_entries.each do |entry| %>
    <tr class="transaction-entry-info">
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td class="account"><%= link_to entry.account.name, entry.account if entry.account %></td>
      <td class="currency amount"><%= currency_format(entry.debit_amount) %></td>
    </tr>
  <% end %>
<% end.empty? %>
  <tr><td>No Transactions yet</td></tr>
<% end %>
</table>

app/views/tranxactions/_transaction_entry_fields.html.erb
<tr class="fields">
  <td>
    <%= f.hidden_field :account_id %>
    <%= text_field_tag :account_id, f.object.account ? f.object.account.name : '', :"data-autocomplete" => transaction_entries_autocomplete_account_name_path, :"data-id-element" => "#" + form_tag_id(f.object_name, :account_id), :tabindex => autotab %>
  </td>
  <td>
    <%= f.text_field :debit_amount, :tabindex => autotab, :class => 'input-debit-amount' + (f.object.debit_amount.blank? ? '' : ' manual-input') %><br />
  </td>
  <td>
    <%= link_to_remove_fields "remove", f, :class => 'remove-transaction-entry' %>
  </td>
</tr>

app/views/tranxactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', tranxactions_path %>

app/views/tranxactions/index.html.erb
<%= render 'quick_create' %>
<h1>Listing transactions</h1>
<h3><%= link_to 'Create Transaction', new_tranxaction_path %></h3>
<%= will_paginate @transactions %>
<%= render "tranxactions/transaction_entries", :tranxactions => @transactions %>

app/views/tranxactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', tranxactions_path %>

app/views/tranxactions/show.html.erb
<h3><div class="link-button"><%= link_to 'Create Account', new_account_path, :tabindex => autotab %></div>
    <div class="link-button"><%= link_to 'Create Transaction', new_tranxaction_path, :tabindex => autotab %></div>
    <div class="clear"></div>
</h3>
<%= render "tranxactions/transaction_entries", :tranxactions => [@transaction] %>
<div>
<%= link_to 'Edit', edit_tranxaction_path(@transaction) %> |
<%= link_to 'Back', tranxactions_path %>
</div>
<br />

<%= render 'quick_create' %>