config/routes.rb
Ezbk::Application.routes.draw do
  root :to => 'accounts#index'
  get 'accounts/autocomplete_account_name'
  get 'transaction_entries/autocomplete_account_name' => 'accounts#autocomplete_account_name'
  get 'tranxactions/autocomplete_transaction_tostring'
  post 'tranxactions/quick_create'
  post 'tranxactions/preview_fare_bus'
  post 'tranxactions/preview_fare_mtr'

  resource :user_session
  match 'login' => "user_sessions#new", :as => 'login', via: [:get, :post]
  match 'logout' => "user_sessions#destroy", :as => 'logout', via: [:get, :post, :delete]
  resources :users

  get 'accounts/expense_report' => 'accounts#report'
  resources :accounts
  resources :transaction_entries
  resources :tranxactions do
    resources :transaction_entries
  end

end

app/models/transaction_entry.rb
class TransactionEntry < ActiveRecord::Base
  after_destroy :calculate_account_current_balance
  after_save :calculate_account_current_balance
  belongs_to :tranxaction, :foreign_key => 'tranxaction_id'
  belongs_to :account, :foreign_key => 'account_id', :touch => true
  validates_presence_of :account_id
  validates_presence_of :debit_amount
  validates_numericality_of :debit_amount

  def calculate_account_current_balance
    self.account.save!
  end

  def account_balance=(value)
    self.account_balance = value
  end
end

app/controllers/transaction_entries_controller.rb
class TransactionEntriesController < ApplicationController
  # GET /transaction_entries
  # GET /transaction_entries.json
  def index
    @transaction_entries = TransactionEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @transaction_entries }
    end
  end

  # GET /transaction_entries/1
  # GET /transaction_entries/1.json
  def show
    @transaction_entry = TransactionEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @transaction_entry }
    end
  end

  # GET /transaction_entries/new
  # GET /transaction_entries/new.json
  def new
    @transaction_entry = TransactionEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @transaction_entry }
    end
  end

  # GET /transaction_entries/1/edit
  def edit
    @transaction_entry = TransactionEntry.find(params[:id])
  end

  # POST /transaction_entries
  # POST /transaction_entries.json
  def create
    #@transaction_entry = TransactionEntry.new(params[:transaction_entry])
    @transaction_entry = TransactionEntry.new(params.require(:transaction_entry).permit(:debit_amount, :tranxaction_id, :account_id))

    respond_to do |format|
      if @transaction_entry.save
        format.html { redirect_to @transaction_entry, :notice => 'Transaction entry was successfully created.' }
        format.json { render :json => @transaction_entry, :status => :created, :location => @transaction_entry }
      else
        format.html { render :action => "new" }
        format.json { render :json => @transaction_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /transaction_entries/1
  # PUT /transaction_entries/1.json
  def update
    @transaction_entry = TransactionEntry.find(params[:id])

    respond_to do |format|
      #if @transaction_entry.update_attributes(params[:transaction_entry])
      if @transaction_entry.update_attributes(params.require(:transaction_entry).permit(:debit_amount, :tranxaction_id, :account_id))
        format.html { redirect_to @transaction_entry, :notice => 'Transaction entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @transaction_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /transaction_entries/1
  # DELETE /transaction_entries/1.json
  def destroy
    @transaction_entry = TransactionEntry.find(params[:id])
    @transaction_entry.destroy

    respond_to do |format|
      format.html { redirect_to transaction_entries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/transaction_entries_helper.rb
module TransactionEntriesHelper
end

app/helpers/transaction_entry_helper.rb
module TransactionEntryHelper
end

app/views/transaction_entries/_form.html.erb
<%= form_for(@transaction_entry) do |f| %>
  <% if @transaction_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction_entry.errors.count, "error") %> prohibited this transaction_entry from being saved:</h2>

      <ul>
      <% @transaction_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account_id %>
    <%= f.number_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :debit_amount %>
    <%= f.text_field :debit_amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transaction_entries/edit.html.erb
<h1>Editing transaction_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction_entry %> |
<%= link_to 'Back', transaction_entries_path %>

app/views/transaction_entries/index.html.erb
<h1>Listing transaction_entries</h1>

<table>
  <tr>
    <th>Transaction ID</th>
    <th>Transaction Date</th>
    <th>Account ID</th>
    <th>Account Name</th>
    <th>Debit Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transaction_entries.each do |transaction_entry| %>
  <tr>
    <td><%= transaction_entry.transaction.id %></td>
    <td><%= transaction_entry.tranxaction.transaction_date %></td>
    <td><%= transaction_entry.account.id %></td>
    <td><%= transaction_entry.account.name %></td>
    <td><%= transaction_entry.debit_amount %></td>
    <td><%= link_to 'Show', transaction_entry %></td>
    <td><%= link_to 'Edit', edit_transaction_entry_path(transaction_entry) %></td>
    <td><%= link_to 'Destroy', transaction_entry, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction entry', new_transaction_entry_path %>

app/views/transaction_entries/new.html.erb
<h1>New transaction_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', transaction_entries_path %>

app/views/transaction_entries/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_transaction_entry_path(@transaction_entry) %> |
<%= link_to 'Back', transaction_entries_path %>