config/routes.rb
Ezbk::Application.routes.draw do
  root :to => 'accounts#index'
  get 'accounts/autocomplete_account_name'
  get 'transaction_entries/autocomplete_account_name' => 'accounts#autocomplete_account_name'
  get 'tranxactions/autocomplete_transaction_tostring'
  post 'tranxactions/quick_create'
  post 'tranxactions/preview_fare_bus'
  post 'tranxactions/preview_fare_mtr'

  resource :user_session
  match 'login' => "user_sessions#new", :as => 'login', via: [:get, :post]
  match 'logout' => "user_sessions#destroy", :as => 'logout', via: [:get, :post, :delete]
  resources :users

  get 'accounts/expense_report' => 'accounts#report'
  resources :accounts
  resources :transaction_entries
  resources :tranxactions do
    resources :transaction_entries
  end

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_help.html.erb
<div id="help" style="display: none;">
  <div id="close_help_button"><%= link_to 'Close', '#' %></div>
  <div class="clear"></div>
  <h1>Keyboard Shortcuts</h1>
  <table id="keyboard_shortcuts-part2">
    <tr><td class="help-key">t</td><td class="help-description">Show Transactions</td></tr>
    <tr><td class="help-key">Shift+t</td><td class="help-description">Create Transaction</td></tr>
    <tr><td class="help-key">q / Tab</td><td class="help-description">Focus on "Quick Create Transaction"</td></tr>
  </table>
  <table id="keyboard_shortcuts-part1">
    <tr><td class="help-key">b</td><td class="help-description">Show Balance Sheet</td></tr>
    <tr><td class="help-key">i</td><td class="help-description">Show Income Statement</td></tr>
    <tr><td class="help-key">Shift+a</td><td class="help-description">Create Account</td></tr>
    <tr><td class="help-key">?</td><td class="help-description">Show this help window</td></tr>
  </table>
  <div class="clear"/>
  <h1>Brief Explanation on Debit +ve/-ve sign</h1>
  <p>Assets - Liabilities = Income - Expense + Equity<br />
  (Cash + Bank Account + Octopus + Receivables) - (loans) = (Salary + Interest Income) - (Transportation + Dinner + Whatever)</p>
  <p>Positive debit means an increase in the left hand side of the equation. All amounts in the transactions are entered as debit. </p>

  <p>For a journey of West Rail from Yuen Long to Hung Hom using Octopus, it means:</p>
  <ol><li>A decrease of $18.6 in Asset:Octopus;</li><li>An increase of $18.6 in Expense:Transportation.</li></ol>
  <p>You will enter 18.6 for Transportation (debit) and -18.6 for Octopus (credit)</p>
</div>

app/views/layouts/_menu.html.erb
<div class="user-menu">
  <div class="nav_links">
    <ul id="nav-menu">
    <% if current_user %><%= current_user.login %><% end %>
      <li id="help_button" class="help"><%= link_to 'Help', '#' %></li>
      <li><% if current_user %><%= link_to 'Logout', logout_path, :method => :delete %> <% end %></li>
    </ul>
  </div>
</div>
  <div class="nav_links">
    <ul id="nav-menu">
      <li><%= link_to 'LRT', 'http://www.mtr.com.hk/en/customer/lr_jp/', :class => 'external', :target => '_blank' %></li>
      <li><%= link_to 'MTR Fares', 'http://tw.piliapp.com/hongkong-mtr/', :class => 'external', :target => '_blank' %></li>
      <li><%= link_to 'MTR Codes', 'http://hkrail.wikia.com/wiki/%E6%B8%AF%E9%90%B5%E8%BB%8A%E7%AB%99%E4%BB%A3%E8%99%9F', :class => 'external', :target => '_blank' %></li>
      <li><%= link_to 'KMB', 'http://www.kmb.hk/tc/services/search.html', :class => 'external', :target => '_blank' %></li>
      <li><%= link_to 'CityBus', 'http://www.nwstbus.com.hk/', :class => 'external', :target => '_blank' %></li>
    </ul>
  </div>
  <div class="nav_links">
    <ul id="nav-menu">
      <li class="accounts-bs"><%= link_to 'Balance Sheet', accounts_path(:stmt_type => 'bs') %></li>
      <li class="accounts-is"><%= link_to 'Income Stmt', accounts_path(:stmt_type => 'is') %></li>
      <li class="transactions"><%= link_to 'Transactions', tranxactions_path %></li>
      <li class="expense_report"><%= link_to 'Expense Report', accounts_expense_report_path %></li>
    </ul>
  </div>
  <div class="clear"></div>
  <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Personal Finance Management</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag 'jquery-ui-1.8.20.custom.css' %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body class="<%= @page_name %>">
    <div id="container">
      <%= render :partial => 'layouts/menu' %>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}", :class => "flash" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
    <%= render :partial => 'layouts/help' %>
    <%= yield(:javascripts) %>
    <script type="text/javascript">
      <%= raw hotkey_for_path_js('t', tranxactions_path) %>
      <%= raw hotkey_for_path_js('shift+t', new_tranxaction_path) %>
      <%= raw hotkey_for_path_js('n', new_tranxaction_path) %>
      <%= raw hotkey_for_path_js('shift+a', new_account_path) %>
      <%= raw hotkey_for_path_js('b', accounts_path(:stmt_type => 'bs')) %>
      <%= raw hotkey_for_path_js('i', accounts_path(:stmt_type => 'is')) %>
      <%= raw hotkey_for_path_js('e', accounts_expense_report_path) %>
      $(document).bind('keyup', 'q', function(evt){ 
        $('#transaction_date').focus();
      });
      $(document).bind('keyup', 'shift+/', show_help);
      $(document).bind('keyup', 'esc', hide_help);
      $('#help_button').click(show_help);
      $('#close_help_button').click(hide_help);
      $(document).ready(function(){
        $('#tranxaction_transaction_date').focus();
        $('#account_name').focus();
        $('#user_session_login').focus();
      });
    </script>
  </body>
</html>