config/routes.rb
Ezbk::Application.routes.draw do
  root :to => 'accounts#index'
  get 'accounts/autocomplete_account_name'
  get 'transaction_entries/autocomplete_account_name' => 'accounts#autocomplete_account_name'
  get 'tranxactions/autocomplete_transaction_tostring'
  post 'tranxactions/quick_create'
  post 'tranxactions/preview_fare_bus'
  post 'tranxactions/preview_fare_mtr'

  resource :user_session
  match 'login' => "user_sessions#new", :as => 'login', via: [:get, :post]
  match 'logout' => "user_sessions#destroy", :as => 'logout', via: [:get, :post, :delete]
  resources :users

  get 'accounts/expense_report' => 'accounts#report'
  resources :accounts
  resources :transaction_entries
  resources :tranxactions do
    resources :transaction_entries
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  include ActiveModel::Dirty
  before_destroy :delete_associated_transactions
  before_save :default_values
  before_save :calculate_current_balance
  after_save :save_original_parent_accounts
  after_save :save_parent_accounts
#  after_save :upon_editing_opening_balance
  #:current_balance
  belongs_to :user
  belongs_to :parent, :class_name => 'Account'
  has_many :children, -> { order(:name) }, :class_name => 'Account', :foreign_key => 'parent_id', :dependent => :destroy
  has_many :transaction_entries
  has_many :tranxactions, :through => :transaction_entries
  scope :of, ->(user) { where(:user_id => user.id) }
  scope :root_accounts, -> { where(:parent_id => nil).order(:name) }
  validates :name, :length => { :minimum => 3 }

  def full_name(prefix = false)
    (self.parent ? self.parent.full_name(true) : "") + self.name + (prefix ? ":" : "")
  end

  def depth
    self.parent ? (1+self.parent.depth) : 0
  end

  def within_depth(depth)
    return self if depth == 0
    self.children.empty? ? self : self.children.map{|acc| acc.within_depth(depth-1) }.flatten
  end

  def descendants
    ([self] + (!self.children.empty? ? self.children.map{|acc| acc.descendants } : [])).flatten
  end

  def upon_editing_opening_balance
    if self.opening_balance_changed?
      self.update_transaction_entry_balances
    end
  end

  def update_transaction_entry_balances()
#    starting_entry ||= self.transaction_entries.
    transaction_entries = self.transaction_entries.all(:joins => :tranxaction, :order => 'tranxactions.transaction_date, tranxactions.id')
    transaction_entries.reduce(self.opening_balance) do |balance, entry|
      entry.account_balance = balance + entry.debit_amount
      entry.save!
      entry.account_balance
    end
  end

  def delete_associated_transactions
    self.tranxactions.each(&:destroy)
  end

  def default_values
    self.opening_balance ||= 0
  end

  def calculate_current_balance
    self.current_balance = self.calculate_own_balance + self.children.reduce(0) do |sum, a|
      sum + a.calculate_current_balance
    end
  end

  def calculate_own_balance
    return self.transaction_entries.reduce(self.opening_balance) do |sum, t|
      sum + t.debit_amount
    end
  end

  def save_original_parent_accounts
    if self.parent_id_changed?
      Account.find(self.parent_id_was).save! if self.parent_id_was
    end
  end

  def save_parent_accounts
    self.parent.save! if self.parent
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :require_user
  before_action :require_accounts
  before_action :set_page_name

  def set_page_name
    @page_name = "accounts-" + (params[:stmt_type] == 'bs' ? 'bs' : 'is')
  end

  def autocomplete_account_name
    @return_list = current_user_accounts.where("name ilike '%" + params[:term] + "%'").map do |a|
      {:id => a.id, :value => a.name}
    end
    render :json => @return_list
  end

  def require_accounts
    if current_user_accounts.blank?
      create_default
      return true
    end
  end

  def report
    @page_name = "expense_report"
    expense_transactions=Tranxaction.joins(:transaction_entries => :account).where("transaction_entries.account_id" => Account.of(current_user).find_by_name("Expenses").descendants.map{|a| a.id})
    @summary = expense_transactions.select("accounts.id, accounts.name, extract(year from tranxactions.transaction_date) as year, extract(month from tranxactions.transaction_date) as month,sum(transaction_entries.debit_amount) as total").group("accounts.id, accounts.name, year, month").order("accounts.parent_id, accounts.name, year, month")
    @accounts = expense_transactions.select("accounts.id, accounts.name").group("accounts.id, accounts.name").order("accounts.name")
    @periods = expense_transactions.select("extract(year from tranxactions.transaction_date) as year, extract(month from tranxactions.transaction_date) as month").group("year, month").order("year desc, month desc")

    is_amounts_query = current_user_accounts.joins(:transaction_entries => :tranxaction).
#                       where("transactions.transaction_date" => ("2013-02-01 00:00:00")..("2013-02-28 23:59:59")).
                       select("accounts.id, accounts.name, sum(transaction_entries.debit_amount) as total_amount").group("accounts.id, accounts.name").
                       order("accounts.name")
    @is_amounts = Hash[is_amounts_query.map { |p| [p.id, p] }]
  end

  def get_amount(account_id, hash)
    if hash.has_key?(account_id)
      hash[account_id].total_amount
    else
      0
    end
  end

  # GET /accounts
  # GET /accounts.json
  def index
    is_amounts_query = current_user_accounts.joins(:transaction_entries => :tranxaction).
                       where("tranxactions.transaction_date" => (Time.now.beginning_of_month())..(Time.now.end_of_month())).
                       select("accounts.id, accounts.name, sum(transaction_entries.debit_amount) as total_amount").group("accounts.id, accounts.name").
                       order("accounts.name")
    @is_amounts = Hash[is_amounts_query.map { |p| [p.id, p] }]

    @accounts = current_user_accounts.where(:name => params[:stmt_type] == 'bs' ? ['Assets', 'Liabilities'] : ['Incomes', 'Expenses'])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = current_user_accounts.find(params[:id])
    @transactions = @account.tranxactions.paginate(:page => params[:page]).order("transaction_date DESC, id DESC")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = current_user_accounts.find(params[:id])
  end

  def create_default
    assets = current_user.accounts.build({:name => 'Assets'})
    assets.save!
      bank_account = current_user.accounts.build({:name => 'Bank Account', :parent_id => assets.id}).save!
      cash = current_user.accounts.build({:name => 'Cash', :parent_id => assets.id}).save!
      octopus = current_user.accounts.build({:name => 'Octopus', :parent_id => assets.id}).save!
      receivables = current_user.accounts.build({:name => 'Receivables/Payable', :parent_id => assets.id})
      receivables.save!
        someone = current_user.accounts.build({:name => 'Someone', :parent_id => receivables.id}).save!
    equities = current_user.accounts.build({:name => 'Equities'})
    equities.save!
    expenses = current_user.accounts.build({:name => 'Expenses'})
    expenses.save!
      family = current_user.accounts.build({:name => 'Family', :parent_id => expenses.id}).save!
      food = current_user.accounts.build({:name => 'Food', :parent_id => expenses.id})
      food.save!
        breakfast = current_user.accounts.build({:name => 'Breakfast', :parent_id => food.id}).save!
        dinner = current_user.accounts.build({:name => 'Dinner', :parent_id => food.id}).save!
        lunch = current_user.accounts.build({:name => 'Lunch', :parent_id => food.id}).save!
        snacks = current_user.accounts.build({:name => 'Snacks and Drinks', :parent_id => food.id}).save!
      medical = current_user.accounts.build({:name => 'Medical', :parent_id => expenses.id}).save!
      misc = current_user.accounts.build({:name => 'Misc', :parent_id => expenses.id}).save!
      recreation = current_user.accounts.build({:name => 'Recreation', :parent_id => expenses.id}).save!
      transportation = current_user.accounts.build({:name => 'Transportation', :parent_id => expenses.id}).save!
    incomes = current_user.accounts.build({:name => 'Incomes'})
    incomes.save!
      salaries = current_user.accounts.build({:name => 'Salaries', :parent_id => incomes.id}).save!
    liabilities = current_user.accounts.build({:name => 'Liabilities'})
    liabilities.save!
  end

  # POST /accounts
  # POST /accounts.json
  def create
    #@account = current_user.accounts.build(params[:account].except(:user_id))
    @account = current_user.accounts.build(params.require(:account).permit(:name, :parent_id, :opening_balance))

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, :notice => 'Account was successfully created.' }
        format.json { render :json => @account, :status => :created, :location => @account }
      else
        format.html { render :action => "new" }
        format.json { render :json => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = current_user_accounts.find(params[:id])

    respond_to do |format|
      #if @account.update_attributes(params[:account])
      if @account.update_attributes(params.require(:account).permit(:name, :parent_id, :opening_balance))
        format.html { redirect_to accounts_path, :notice => 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = current_user_accounts.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  private

  def current_user_accounts
    Account.of(current_user)
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
  def get_account_value(amounts, account)
    account.children.reduce(0){|sum, acc| get_account_value(amounts, acc)+sum } +
    (amounts.has_key?(account.id) ? amounts[account.id]["total_amount"] : 0)
  end

  def get_saving_amount(amounts, accounts)
    - get_account_value(amounts, accounts.where(:name => 'Incomes').first) -
    get_account_value(amounts, accounts.where(:name => 'Expenses').first)
  end
end

app/views/accounts/_account.html.erb
  <tr class="account-level-<%= level %>">
    <td><div class="button"><%= link_to edit_icon, edit_account_path(account) %></div></td>
    <td><div class="button"><%= link_to destroy_icon, account, :confirm => 'Are you sure?', :method => :delete %></div></td>
    <td class="account-name"><%= link_to account.name, account %></td>
    <td class="currency account-currency<%= " negative" if account.current_balance<0 %>"><%= link_to currency_format(account.current_balance), account %></td>
    <td class="currency account-currency<%= " negative" if account.current_balance<0 %>"><%= link_to currency_format(get_account_value(@is_amounts, account)), account %></td>
  </tr>
  <% if !account.children.empty? %>
    <%= render :partial => 'account', :collection => account.children, :locals => {:level => level + 1 } %>
  <% end %>

app/views/accounts/_form.html.erb
<ul id="form-validation-messages" style="display: none;"></ul>
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :tabindex => autotab %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.hidden_field :parent_id %>
    <%= text_field_tag :parent_id, f.object.parent ? f.object.parent.name : '', :"data-autocomplete" => accounts_autocomplete_account_name_path, :"data-id-element" => "#" + form_tag_id(f.object_name, :parent_id), :tabindex => autotab %>
  </div>
  <div class="field">
    <%= f.label :opening_balance %><br />
    <%= f.text_field :opening_balance, :tabindex => autotab %>
  </div>
  <div class="actions">
    <%= f.submit :tabindex => autotab %>
  </div>
<% end %>

<% content_for :javascripts do %>
<script type="text/javascript">
  $('#new_account').validate({
    ignore: [],
    errorLabelContainer: "#form-validation-messages",
    wrapper: 'li',
    rules: {
      "account[name]": {
         required: true,
         minlength: 3
      },
      "account[parent_id]": {
        required: {
          depends: function(element){
            return $('#parent_id').val()!="";
          }
        }
      }
    },
    messages: {
      "account[name]": "At least 3 characters required",
      "account[parent_id]": "You have entered something in the Parent Account but not selected the account"
    }
  });
</script>
<% end %>

app/views/accounts/_transaction.html.erb
  <tr class="transaction-info">
    <td><%= transaction.transaction_date %></td>
    <td><%= transaction.description %></td>
    <td></td>
    <td></td>
    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
  <% transaction.transaction_entries.each do |entry| %>
    <tr class="transaction-entry-info">
      <td></td>
      <td></td>
      <td><%= entry.account.name %></td>
      <td class="currency"><%= number_with_precision(entry.debit_amount, :delimiter => ',', :precision => 2) %></td>
      <td></td>
      <td></td>
    </tr>
  <% end %>

app/views/accounts/_tranxaction.html.erb
  <tr class="transaction-info">
    <td><%= transaction.transaction_date %></td>
    <td><%= transaction.description %></td>
    <td></td>
    <td></td>
    <td><%= link_to 'Edit', edit_tranxaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
  <% transaction.transaction_entries.each do |entry| %>
    <tr class="transaction-entry-info">
      <td></td>
      <td></td>
      <td><%= entry.account.name %></td>
      <td class="currency"><%= number_with_precision(entry.debit_amount, :delimiter => ',', :precision => 2) %></td>
      <td></td>
      <td></td>
    </tr>
  <% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<%= render 'tranxactions/quick_create' %>
<h1>Listing accounts</h1>
<h3><div class="link-button"><%= link_to 'Create Account', new_account_path, :tabindex => autotab %></div>
    <div class="link-button"><%= link_to 'Create Transaction', new_tranxaction_path, :tabindex => autotab %></div>
    <div class="clear"></div>
</h3>
<div class="field">
  <%= check_box_tag 'hide-zero-accounts' %>
  <%= label_tag 'hide-zero-accounts', 'Hide accounts with zero balance' %>
</div>

<table id="account-list">
  <tr>
    <th></th>
    <th></th>
    <th>Account Name</th>
    <th>Current Balance</th>
    <th>Monthly Balance</th>
  </tr>

<%= render :partial => 'account',:collection => @accounts.root_accounts, :locals => {:level => 0} %>
<% if params[:stmt_type] == 'is' %>
  <tr>
    <td></td>
    <td></td>
    <td>Savings</td>
    <td></td>
    <td class="currency"><%=currency_format(get_saving_amount(@is_amounts, @accounts))%></td>
  </tr>
<% end %>
</table>

<br />

<% content_for :javascripts do %>
<script type="text/javascript">
$('#hide-zero-accounts').click(function(evt){
  if(this.checked){
    $('table#account-list tbody tr').filter(function(index){
      return $(this).find('td.account-currency a').first().html() == "0.00";
    }).hide();
  }else{
    $('table#account-list tr').show();
  }
});
</script>
<% end %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/report.html.erb
<%= render 'tranxactions/quick_create' %>
<h1>Listing accounts</h1>
<h3><div class="link-button"><%= link_to 'Create Account', new_account_path, :tabindex => autotab %></div>
    <div class="link-button"><%= link_to 'Create Transaction', new_tranxaction_path, :tabindex => autotab %></div>
    <div class="clear"></div>
</h3>
<div class="field">
  <%= check_box_tag 'hide-zero-accounts' %>
  <%= label_tag 'hide-zero-accounts', 'Hide accounts with zero balance' %>
</div>

<table>
  <thead><tr>
    <th></th><% @periods.each do |item| %><th><%=item.year.to_i %> <%=item.month.to_i %></th><% end %>
  </tr></thead>
  <tbody>
    <% @accounts.each do |account| %>
    <tr>
      <th><%=account.name %></th>
      <% @periods.each do |period| %>
        <td class="currency" style="padding: 8px;">
          <% entry = @summary.select {|row| row.year == period.year and row.month == period.month and row.id == account.id} %>
          <%=currency_format(entry[0] ? entry[0].total : 0) %>
        </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1>Showing Account - <%= @account.name %></h1>
<table id="account-info" class="center">
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent Account</th>
      <th>Children Account(s)</th>
      <th>Opening Balance</th>
      <th>Current Balance</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @account.name %></td>
      <td><%= @account.parent ? link_to(@account.parent.name, @account.parent) : 'Nil'  %></td>
      <td><% if @account.children.each do |a| %>
             <%= link_to(a.name, a) %>
           <% end.empty?  %>
              Nil
            <% end %>
      </td>
      <td><%= currency_format(@account.opening_balance) %></td>
      <td><%= currency_format(@account.current_balance) %></td>
    </tr>
  </tbody>
</table>

<br>
<div>
<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>
</div>

<h1>Listing Transactions - <%= @account.name %></h1>
<h3><%= link_to 'Create Transaction', new_tranxaction_path %></h3>
<%= will_paginate @transactions %>
<div id="account-transactions-container">
<%= render "tranxactions/transaction_entries", :tranxactions => @transactions %>
</div>

<% content_for :javascripts do %>
  <script type="text/javascript">
    function highlight_account_in_transactions(account_name){
      $('#account-transactions-container a').filter(function(){ return $(this).html() == account_name; }).each(function(index, e){
        $(e).closest("tr").addClass('current-account');
      });
    }

    highlight_account_in_transactions("<%= @account.name %>");
  </script>
<% end %>